juaml/julearn

docs/changes/latest.inc, julearn/pipeline.py, julearn/tests/test_pipeline.py
Here, we want to go for a simpler attempt at solving #122.
Instead of making wrapped params part of wrapper, we just change the getters for `ExtendedPipeline` so that it returns the wrapped object iteself
=> Solve #122

examples/advanced/run_return_confounds.py, julearn/model_selection/available_searchers.py, test-requirements.txt
Use codespell from pip, not from master. 
This will fix the issue that some CI will not pass after codespell is updated. It will only change due to new codespell releases, which will not be as often as commits to the repo.
=> Fix ci, use latest codespell from pip

docs/changes/latest.inc, julearn/transformers/confounds.py
I added the BaseEstimator to the TargetTransformWrapper not the  TargetConfoundRemover
Here, I want to add it to the TargetConfoundRemover as I wanted before
=> ADD BaseEstimator to TargetConfoundRemover #151

julearn/api.py
Expose scikit-learn's `cross_validate` `return_train_scores` parameter.
=> Allow julearn to return train scores

docs/changes/newsfragments/47.feature, examples/03_complex_models/run_hyperparameter_multiple_grids.py, julearn/api.py, julearn/pipeline/merger.py, julearn/pipeline/pipeline_creator.py, julearn/pipeline/test/test_merger.py, julearn/pipeline/test/test_pipeline_creator.py, julearn/prepare.py, julearn/tests/test_api.py, julearn/transformers/dataframe/set_column_types.py
This is from a scikit-learn example:
```Python
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
'C': [1, 10, 100, 1000]},
{'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
clf = GridSearchCV(
SVC(), tuned_parameters, scoring='%s_macro' % score
)
```
This example creates two grids, one for the `rbf` kernel, exploring `gamma`, and one for the `linear` kernel, without testing `gamma`, because it does not make sense.
In order to do this, we need to set the following `model_params`:
```Python
model_params = {
'svm__C': [1, 10, 100, 1000],
'svm__kernel': ['rbf', linear'],
'svm__gamma': [1e-3, 1e-4]
}
```
However, we will be testing different `gamma` options for the `linear` kernel (useless).
We need to find a way of specifying sets of parameters to be tested.
=> [ENH] Allow list of hyperparameter options for tuning

docs/api/viz.rst, docs/changes/contributors.inc, docs/changes/newsfragments/232.misc, docs/conf.py, docs/configuration.rst, docs/getting_started.rst, docs/maintaining.rst, docs/what_really_need_know/cross_validation.rst, docs/what_really_need_know/index.rst, docs/whats_new.rst, ignore_words.txt, pyproject.toml, tox.ini
`codespell` now supports reading config from `pyproject.toml`. This will allow us to keep `tox.ini` clean.
=> [MAINT]: Improve `codespell` support

docs/changes/newsfragments/168.doc, julearn/api.py, julearn/prepare.py
Different links in the documentation are not working. 
For example under julearn.api.run_cross_validation (https://juaml.github.io/julearn/v0.2.3/api.html) this link (https://juaml.github.io/julearn/input.html) appears multiple times but leads to a 404.
=> [DOC]: Not working links in documentation

docs/changes/newsfragments/247.bugfix, julearn/pipeline/pipeline_creator.py, julearn/pipeline/test/test_pipeline_creator.py
If I set a hyperparameter as part of the `PipelineCreator.add` method, without providing several options so there's no tuning involved, the hyperparameter is not set. This only happens when the estimator is not a string but an already instantiated scikit-learn compatible object.
```python
creator = PipelineCreator(problem_type="classification", apply_to="*")
creator.add(DummyClassifier(), strategy="constant", name="dummy")
```
If I then do convert this to a pipeline and check the model:
```python
model = creator.to_pipeline()
print(model.steps[-1][1].get_params())
```
I get this:
```
{'apply_to': ColumnTypes<types={'*'}; pattern=.*>, 'model': DummyClassifier(), 'needed_types': None, 'constant': None, 'random_state': None, 'strategy': 'prior'}
```
that means that the `strategy` was not …
=> [BUG]: Hyperparameters are not set if an estimator is used instead of a string in PipelineCreator

docs/whats_new.rst
The what's new section of the docs is somehow wrong.
=> Fix the what's new section of the docs

docs/changes/newsfragments/251.misc, julearn/conftest.py, julearn/models/tests/test_dynamic.py, julearn/pipeline/test/test_pipeline_creator.py, tox.ini
`pytest-lazy-fixture` breaks in Pytest 8.0.0: https://github.com/TvoroG/pytest-lazy-fixture/issues/65
Ideally, we should ditch this dependency as it is not actively maintained anymore and I do believe that we can achieve the same goal in a different way. It also creates an issue with other tools as the order of the tests is not usually maintained across runs.
=> [MAINT]: Support `pytest >= 8.0.0`

.github/workflows/check-stale.yml, docs/changes/newsfragments/224.misc
Use this action: https://github.com/marketplace/actions/close-stale-issues
To mark issues as stale and later on close them if they have the label _question_ (meaning waiting for a response) and they were not replied in 30 days (stale) and then close (7 more days).
```yaml
name: 'Close stale issues and PRs'
on:
schedule:
- cron: '30 1 * * *'
jobs:
stale:
runs-on: ubuntu-latest
steps:
- uses: actions/stale@v8
with:
stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
days-before-stale: 30
days-before-close: 7
any-of-issue-labels: question
```
_No response_
_No response_
=> [CI]: Mark stale and close issues after inactivity

docs/changes/newsfragments/244.misc, julearn/base/estimators.py, julearn/pipeline/test/test_target_pipeline.py, julearn/tests/test_api.py, julearn/utils/typing.py, pyproject.toml
The first release candidate for scikit-learn 1.4 is available as from 21.12.2023.
We should test compatibility with julearn.
=> [MAINT]: Prepare for scikit-learn 1.4

docs/changes/newsfragments/262.doc, docs/changes/newsfragments/262.enh, docs/changes/newsfragments/262.feature, docs/conf.py, docs/links.inc, examples/99_docs/run_hyperparameters_docs.py, julearn/api.py, julearn/conftest.py, julearn/model_selection/__init__.py, julearn/model_selection/_optuna_searcher.py, julearn/model_selection/_skopt_searcher.py, julearn/model_selection/tests/test_available_searchers.py, julearn/model_selection/tests/test_optuna_searcher.py, julearn/model_selection/tests/test_skopt_searcher.py, julearn/pipeline/pipeline_creator.py, julearn/pipeline/tests/test_pipeline_creator.py, pyproject.toml, tox.ini
Integrate Optuna (https://optuna.org/) for Hyperparameter Tuning as `optuna` searcher, using the `OptunaSearchCV` model.
=> Add optuna option for searchers

README.md, docs/getting_started.rst, docs/links.inc, pyproject.toml
Make `julearn` available via `conda` by adding recipe to [conda-forge](https://conda-forge.org) channel. This will enable users to install `julearn` via:
```shell
conda install -c conda-forge julearn
```
=> [MAINT]: Add `julearn` to `conda-forge`

docs/changes/newsfragments/265.fix, julearn/external/optuna_searchcv.py, julearn/model_selection/_optuna_searcher.py, julearn/pipeline/tests/test_pipeline_creator.py, pyproject.toml, tox.ini
Since the current `OptunaSearchCV` has an issue with respect of scikit-learn's implementation (https://github.com/optuna/optuna-integration/issues/118), this PR includes an internal implementation which is fully compatible with scikit-learn.
Particularly, the `fit` method uses a different study in each call, thus respecting the scikit-learn convention of learning in each call and overriding any previous fit call. The implementation in the optuna-integration package will continue training. This creates a test-to-train leakage when used with scikit-learn's `cross_validate` function, which is also used by julearn.
=> Provide internal implementation of OptunaSearchCV

docs/changes/newsfragments/268.bugfix, julearn/model_selection/_optuna_searcher.py, julearn/model_selection/tests/test_optuna_searcher.py, julearn/pipeline/pipeline_creator.py, julearn/pipeline/tests/test_merger.py, julearn/transformers/tests/test_jucolumntransformers.py
Using something like this:
```
creator.add(
"rf",
C=IntDistribution(low=100, high=400, step=50),
max_depth=5,
min_samples_split=2,
min_samples_leaf=2,
)
```
Would not work on scikit-learn 1.3, raising the errror:
```
sklearn.utils._param_validation.InvalidParameterError: The 'n_estimators' parameter of RandomForestClassifier must be an int in the range [1, inf). Got IntDistribution(high=400, log=False, low=100, step=50) instead.
```
Apparently this is not an issue in the new scikit-learn (or even in the test suit).
This PR fixes that.
=> Fix usage of optuna distributions

docs/changes/newsfragments/270.enh, docs/getting_started.rst, docs/whats_new.rst, examples/99_docs/run_hyperparameters_docs.py, julearn/api.py, julearn/inspect/tests/test_inspector.py, julearn/pipeline/pipeline_creator.py, pyproject.toml, tox.ini
Currently, obtaining and inspector `return_inspector=True` requires that a final model is fit (`return_estimator='all'`). This is to be able to inspect the final model's parameters. Nevertheless, is not technically required if we need to inspect the fold-wise predictions.
This PR fixes that requirements, so either `'cv'` or `'all'` can be used, avoiding to fit final models on large complex models that can take up to hours.
=> [ENH] Remove final model fit requirement for inspector

docs/api/main.rst, docs/changes/newsfragments/271.enh, julearn/__init__.py, julearn/api.py, julearn/prepare.py, julearn/tests/test_api.py
Implements #113 by adding a `run_fit` method to the API, which does not perform cross validation but rather fits the "final"model.
=> Add fit method to API

docs/changes/newsfragments/274.enh, docs/configuration.rst, examples/02_inspection/plot_preprocess.py, examples/04_confounds/run_return_confounds.py, examples/99_docs/run_model_inspection_docs.py, julearn/config.py, julearn/inspect/_pipeline.py, julearn/inspect/tests/test_pipeline.py, julearn/pipeline/pipeline_creator.py, julearn/pipeline/tests/test_pipeline_creator.py, julearn/tests/test_api.py, julearn/transformers/ju_column_transformer.py
Currently, if a step does apply to anything different that `"continuous"`, it will be wrapped in a column transformer.
This is unoptimal as there is an overhead (which also invoves joblib) when this happens.
This PR fixes that by really checking the `apply_to` of the step with the `X_types` of the data. If the step really applies to a subset of features, then it will wrapped in a column transformer.
=> [ENH]: Optimise step wrapping

docs/changes/newsfragments/275.enh, julearn/api.py, julearn/model_selection/final_model_cv.py, julearn/model_selection/tests/test_final_model_cv.py, julearn/models/tests/test_models.py, julearn/tests/test_api.py, pyproject.toml
When the final model is expected, the CV iterator ads one more split that trains on all data.
This PR inverts the order, so the first split is the final model.
This has no impact on the results, but has an impact on compute time when masively parallelised (e.g. using htcondor).
=> Invert order of CV so it runs the largest first

docs/changes/newsfragments/268.bugfix, docs/changes/newsfragments/270.enh, docs/changes/newsfragments/271.enh, docs/changes/newsfragments/274.enh, docs/changes/newsfragments/275.enh, docs/changes/newsfragments/293.enh, docs/whats_new.rst
This PR updates the `whats_new.rst` for 0.3.4 release.
=> [MAINT]: Release 0.3.4

docs/api/config.rst, docs/api/index.rst, docs/changes/newsfragments/277.enh, julearn/transformers/dataframe/filter_columns.py
Use the same logic for the `FilterColumns` as for the `JuColumnTransformer`, avoiding parallel calls if not specified by the user.
=> Control parallel column transformer in filter columns
