julearn/pipeline.py, julearn/scoring.py, julearn/transformers/dataframe.py, julearn/transformers/target.py
I added some more docstrings to a couple of the crucial julearn components  to enhance documentation.
=> Docstrings

.coveragerc, .github/workflows/ci.yml, julearn/tests/test_api.py
Added a few tests for the API, comparing that the pipeline fits the sklearn model with the same info.
Updated coverage to fix a reporting issue. Relates to #23
=> Better testing

docs/index.rst, docs/input.rst, examples/basic/plot_groupcv_inspect_svm.py, examples/basic/plot_inspect_random_forest.py, julearn/__init__.py, julearn/api.py, julearn/estimators/available_models.py, julearn/prepare.py, julearn/tests/test_api.py, julearn/tests/test_estimators.py, julearn/tests/test_prepare.py, julearn/utils.py
Implements #21 
Implements #4
Realtes to #23
=> Model select input data

julearn/model_selection.py, julearn/pipeline.py, julearn/scoring.py
Changed a couple of methods to private. 
Also `_transform_target` is the old `trasform_target`. 
The new one works as you described from what I can see.
=> Extended pipeline refactor

docs/hyperparameters.rst, docs/links.inc, julearn/api.py, julearn/pipeline.py, julearn/prepare.py, julearn/tests/test_api.py, julearn/tests/test_estimators.py, julearn/tests/test_prepare.py
* Change `model_selection` to `model_params` in `run_cross_validation`
* Add `search` and `search_params` to allow for GridSearchCV and RandomizedSearchCV.
=> Implement #41

docs/links.inc, docs/pipeline.rst, julearn/api.py, julearn/pipeline.py, julearn/tests/test_pipeline.py, julearn/tests/test_prepare.py, julearn/transformers/dataframe.py
Starting to work on #23 #28  #39
=> Remove redundent function make_pipeline

docs/contributing.rst, docs/links.inc
=> Example docs

docs/contributing.rst, examples/advanced/run_hyperparameter_tuning.py, examples/basic/plot_groupcv_inspect_svm.py, examples/basic/plot_inspect_random_forest.py, julearn/api.py, julearn/tests/test_api.py, julearn/utils/testing.py
=> Added option to return estimator for each CV

docs-requirements.txt, docs/conf.py, docs/contributing.rst
@fraimondo  What do you think ?
For me it looks a bit more modern, but it was fine before as well of course.
=> Docs theme

julearn/api.py, julearn/tests/test_api.py, julearn/utils/testing.py
=> Add fold idx in results

Makefile, dev-requirements.txt, docs/contributing.rst, docs/installation.rst
Added dev-requirements.txt to fix #99. Change doc to make it explicit that `_version.py` should not be committed (fix #100)
=> Dev req fix

docs/changes/latest.inc, julearn/model_selection.py, julearn/prepare.py, julearn/scoring.py, julearn/tests/test_api.py, julearn/tests/test_prepare.py
We had a small bug with using multiprocessing and using the `wrap_search` function. 
Because `wrap_search` is not pickable, it was not being usable by multiprocessing in sklearns parallel_backend.
=> Multiprocessing Bug

docs/changes/latest.inc, julearn/prepare.py, julearn/tests/test_prepare.py
Now it will raise an error if the column names are not strings
=> fix for #77

docs/changes/latest.inc, examples/basic/plot_groupcv_inspect_svm.py, julearn/transformers/target.py
=> [BUG] fix #151

examples/basic/plot_transform_until.py
Update example to inspect preprocessing steps with the new API.
=> updated example to inspect preprocessing steps

julearn/transformers/confounds.py
Update the docstrings for DataFrameConfoundRemover for the new api.
=> add/update docstrings to DataFrameConfoundRemover

examples/basic/plot_cm_acc_multiclass.py, examples/basic/plot_groupcv_inspect_svm.py, julearn/base/tests/test_base_models.py, julearn/inspect/__init__.py, julearn/inspect/preprocess.py, julearn/models/tests/test_available_models.py, julearn/models/tests/test_models.py, julearn/transformers/tests/test_transformers.py, julearn/utils/logging.py, julearn/utils/testing.py, julearn/utils/tests/test_logging.py
Updated two examples plot_groupcv_inspect_svm.py and plot_cm_acc_multiclass.py
=> Sk pandas examples

examples/basic/plot_confound_removal_classification.py, julearn/transformers/confounds.py
This PR updates confound removal example and feature inspection in random forest classifier.
=> update confound removal example

docs/api/viz.rst, docs/conf.py, julearn/viz/_scores.py, pyproject.toml
Try to fix the docs not building in CI
=> Fix viz module

julearn/model_selection/continuous_stratified_kfold.py
Remove underscore so variables are cloned (scikit-learn standard)
=> [BUG] Cloning one the CV does not comprise some variables.

docs/changes/newsfragments/224.misc, docs/changes/newsfragments/244.misc, docs/changes/newsfragments/249.bugfix, docs/changes/newsfragments/251.misc, docs/changes/newsfragments/255.bugfix, docs/changes/newsfragments/260.enh, docs/changes/newsfragments/260.misc, docs/changes/newsfragments/262.doc, docs/changes/newsfragments/262.enh, docs/changes/newsfragments/262.feature, docs/whats_new.rst
This PR updates the `whats_new.rst` for 0.3.2 release.
=> [MAINT]: Release 0.3.2

docs/changes/newsfragments/258.doc, docs/changes/newsfragments/265.fix, docs/whats_new.rst
This PR updates the `whats_new.rst` for 0.3.3 release.
=> [MAINT]: Release 0.3.3

.github/workflows/ci-docs.yml, .github/workflows/ci.yml
Update codecov actions from v3 to v4
=> Update codecov actions

README.md, docs/changes/newsfragments/283.doc, examples/00_starting/plot_stratified_kfold_reg.py, examples/00_starting/run_combine_pandas.py, examples/00_starting/run_grouped_cv.py, examples/02_inspection/plot_groupcv_inspect_svm.py, examples/03_complex_models/run_hyperparameter_multiple_grids.py, examples/03_complex_models/run_hyperparameter_tuning.py, examples/99_docs/run_cv_splitters_docs.py, julearn/base/estimators.py, julearn/conftest.py, julearn/inspect/tests/test_preprocess.py, julearn/pipeline/pipeline_creator.py, julearn/scoring/available_scorers.py, julearn/stats/corrected_ttest.py, julearn/transformers/target/ju_transformed_target_model.py, julearn/transformers/target/target_confound_remover.py
This PR adds JuRSE Code Pick shield in README.
=> [DOC]: Update shield in README

README.md, docs/changes/newsfragments/279.doc, julearn/base/column_types.py, julearn/tests/test_prepare.py
Currently the doc is showing the pre-print (arxiv) and not the paper (gigabyte) as the citation for julearn.
=> [DOC] Update citation
